"""Updates to direction table

Revision ID: 2ee4d0179971
Revises: 1af84702a4ce
Create Date: 2023-07-10 15:34:27.524122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee4d0179971'
down_revision = '1af84702a4ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('scaler_id', sa.Integer(), nullable=True))
    op.add_column('directions', sa.Column('fraction_of_variance_explained', sa.Float(), nullable=True))
    op.drop_index('idx_component_index_created_at', table_name='directions')
    op.drop_index('idx_directions_model_layer_type_created_at', table_name='directions')
    op.create_index('idx_directions_model_layer_type_created_at', 'directions', ['model_id', 'layer', 'type', 'component_index', 'created_at'], unique=False)
    op.create_foreign_key('directions_scaler_id_fkey', 'directions', 'scalers', ['scaler_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('directions_scaler_id_fkey', 'directions', type_='foreignkey')
    op.drop_index('idx_directions_model_layer_type_created_at', table_name='directions')
    op.create_index('idx_directions_model_layer_type_created_at', 'directions', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.create_index('idx_component_index_created_at', 'directions', ['component_index', 'created_at'], unique=False)
    op.drop_column('directions', 'fraction_of_variance_explained')
    op.drop_column('directions', 'scaler_id')
    # ### end Alembic commands ###
