"""Add head to directions

Revision ID: a5221a4afad2
Revises: 756aff98252b
Create Date: 2023-07-10 16:20:41.470950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5221a4afad2'
down_revision = '756aff98252b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('head', sa.Integer(), nullable=True))
    op.drop_index('idx_directions_model_layer_type_created_at', table_name='directions')
    op.create_index('idx_directions_model_layer_type_created_at', 'directions', ['model_id', 'layer', 'type', 'head', 'component_index', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_directions_model_layer_type_created_at', table_name='directions')
    op.create_index('idx_directions_model_layer_type_created_at', 'directions', ['model_id', 'layer', 'type', 'component_index', 'created_at'], unique=False)
    op.drop_column('directions', 'head')
    # ### end Alembic commands ###
