"""Tweak some index names, drop the vectors table

Revision ID: c91c5c02be59
Revises: 2bd28a5c5a2f
Create Date: 2023-07-07 19:08:53.559794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c91c5c02be59'
down_revision = '2bd28a5c5a2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vectors_id', table_name='vectors')
    op.drop_table('vectors')
    op.add_column('directions', sa.Column('generated_by_process', sa.String(), nullable=True))
    op.drop_index('idx_directions_model_layer_type_time', table_name='directions')
    op.create_index('idx_directions_model_layer_type_created_at', 'directions', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.create_index('idx_generated_by_process_created_at', 'directions', ['generated_by_process', 'created_at'], unique=False)
    op.drop_index('idx_resids_model_layer_type_time', table_name='resids')
    op.create_index('idx_resids_model_layer_type_created_at', 'resids', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resids_model_layer_type_created_at', table_name='resids')
    op.create_index('idx_resids_model_layer_type_time', 'resids', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.drop_index('idx_generated_by_process_created_at', table_name='directions')
    op.drop_index('idx_directions_model_layer_type_created_at', table_name='directions')
    op.create_index('idx_directions_model_layer_type_time', 'directions', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.drop_column('directions', 'generated_by_process')
    op.create_table('vectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vectors_pkey')
    )
    op.create_index('ix_vectors_id', 'vectors', ['id'], unique=False)
    # ### end Alembic commands ###
