"""Add model and resid

Revision ID: e8ab38fc9d3d
Revises: 9f287d5e4246
Create Date: 2023-07-07 18:30:10.771511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ab38fc9d3d'
down_revision = '9f287d5e4246'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('resids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resid', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resids_model_layer_type', 'resids', ['model_id', 'layer', 'type'], unique=False)
    op.create_index(op.f('ix_resids_id'), 'resids', ['id'], unique=False)
    op.create_index(op.f('ix_resids_model_id'), 'resids', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resids_model_id'), table_name='resids')
    op.drop_index(op.f('ix_resids_id'), table_name='resids')
    op.drop_index('idx_resids_model_layer_type', table_name='resids')
    op.drop_table('resids')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
