"""Remove uniqueness constraint on direction description index

Revision ID: 00cd1eda680f
Revises: dba74d5e9bf7
Create Date: 2023-07-20 00:45:29.775022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cd1eda680f'
down_revision = 'dba74d5e9bf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_direction_user', table_name='direction_descriptions')
    op.create_index('idx_direction_user', 'direction_descriptions', ['direction_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_direction_user', table_name='direction_descriptions')
    op.create_index('idx_direction_user', 'direction_descriptions', ['direction_id', 'user_id'], unique=False)
    # ### end Alembic commands ###
