"""Add generated_by_process index

Revision ID: 08ca044a6049
Revises: 79c1620aa33d
Create Date: 2023-07-24 17:19:44.378545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ca044a6049'
down_revision = '79c1620aa33d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.create_index('idx_scalers_model_generated_layer_type_created_at', 'scalers', ['model_id', 'generated_by_process', 'layer', 'type', 'head', 'created_at'], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scalers_model_generated_layer_type_created_at', table_name='scalers')
    # ### end Alembic commands ###
