"""Add name column to direction table

Revision ID: 160bd707a3c0
Revises: 2ee4d0179971
Create Date: 2023-07-10 15:59:17.366495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160bd707a3c0'
down_revision = '2ee4d0179971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_directions_name'), 'directions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directions_name'), table_name='directions')
    op.drop_column('directions', 'name')
    # ### end Alembic commands ###
