"""Changes to extended_pos_embed

Revision ID: 19e0f8750a2c
Revises: 6c8222141f44
Create Date: 2023-08-03 20:19:50.795316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e0f8750a2c'
down_revision = '6c8222141f44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extended_pos_embeds', sa.Column('type', sa.String(), nullable=False))
    op.alter_column('extended_pos_embeds', 'layer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extended_pos_embeds', 'token_position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extended_pos_embeds', 'tokens_used_to_compute_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('idx_model_layer_hash_token_position', table_name='extended_pos_embeds')
    op.create_index('idx_model_layer_type_hash_token_position', 'extended_pos_embeds', ['model_id', 'layer', 'tokens_used_to_compute_hash', 'token_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_model_layer_type_hash_token_position', table_name='extended_pos_embeds')
    op.create_index('idx_model_layer_hash_token_position', 'extended_pos_embeds', ['model_id', 'layer', 'tokens_used_to_compute_hash', 'token_position'], unique=False)
    op.alter_column('extended_pos_embeds', 'tokens_used_to_compute_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('extended_pos_embeds', 'token_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('extended_pos_embeds', 'layer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('extended_pos_embeds', 'type')
    # ### end Alembic commands ###
