"""Add created_at to resid

Revision ID: 2bd28a5c5a2f
Revises: ef06ff5023b8
Create Date: 2023-07-07 18:59:34.513646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd28a5c5a2f'
down_revision = 'ef06ff5023b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resids', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index('idx_resids_model_layer_type', table_name='resids')
    op.create_index('idx_resids_model_layer_type_time', 'resids', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.create_index(op.f('ix_resids_created_at'), 'resids', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resids_created_at'), table_name='resids')
    op.drop_index('idx_resids_model_layer_type_time', table_name='resids')
    op.create_index('idx_resids_model_layer_type', 'resids', ['model_id', 'layer', 'type'], unique=False)
    op.drop_column('resids', 'created_at')
    # ### end Alembic commands ###
