"""Add index to resids

Revision ID: 4dca427ac24b
Revises: 55a4a8f753cc
Create Date: 2023-07-10 14:49:23.485103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dca427ac24b'
down_revision = '55a4a8f753cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_resids_model_layer_type_head_token_position_ca', 'resids', ['model_id', 'layer', 'type', 'head', 'token_position', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resids_model_layer_type_head_token_position_ca', table_name='resids')
    # ### end Alembic commands ###
