"""Remove dimension from scalers table

Revision ID: 756aff98252b
Revises: 160bd707a3c0
Create Date: 2023-07-10 16:09:50.465039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756aff98252b'
down_revision = '160bd707a3c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scalers', 'dimension')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scalers', sa.Column('dimension', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
