"""Add generated_by_process to scalers

Revision ID: 79c1620aa33d
Revises: 21f411bcd50f
Create Date: 2023-07-24 17:18:23.425860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c1620aa33d'
down_revision = '21f411bcd50f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scalers', sa.Column('generated_by_process', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scalers', 'generated_by_process')
    # ### end Alembic commands ###
