"""Improve DirectionDescription and User

Revision ID: 7d008b9c9810
Revises: a5221a4afad2
Create Date: 2023-07-12 18:20:51.558834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d008b9c9810'
down_revision = 'a5221a4afad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction_descriptions', sa.Column('description', sa.String(), nullable=False))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('direction_descriptions', 'description')
    # ### end Alembic commands ###
