"""Upvotes

Revision ID: 84475365fdb4
Revises: 7d008b9c9810
Create Date: 2023-07-13 17:12:04.885103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84475365fdb4'
down_revision = '7d008b9c9810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction_descriptions', sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
    op.create_index('idx_direction_upvotes_created_at', 'direction_descriptions', ['direction_id', 'upvotes', 'created_at'], unique=False)
    op.create_index('idx_direction_user', 'direction_descriptions', ['direction_id', 'user_id'], unique=True)
    op.create_index('idx_user_upvotes_created_at', 'direction_descriptions', ['user_id', 'upvotes', 'created_at'], unique=False)
    op.create_index(op.f('ix_direction_descriptions_upvotes'), 'direction_descriptions', ['upvotes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direction_descriptions_upvotes'), table_name='direction_descriptions')
    op.drop_index('idx_user_upvotes_created_at', table_name='direction_descriptions')
    op.drop_index('idx_direction_user', table_name='direction_descriptions')
    op.drop_index('idx_direction_upvotes_created_at', table_name='direction_descriptions')
    op.drop_column('direction_descriptions', 'upvotes')
    # ### end Alembic commands ###
