"""Alembic updates

Revision ID: cefbc3c6ce4d
Revises: d7c29a0ee7fe
Create Date: 2023-07-07 19:59:48.572800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefbc3c6ce4d'
down_revision = 'd7c29a0ee7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('text', sa.String(), nullable=False))
    op.drop_index('ix_prompts_prompt', table_name='prompts')
    op.create_index(op.f('ix_prompts_text'), 'prompts', ['text'], unique=False)
    op.drop_column('prompts', 'prompt')
    op.add_column('resids', sa.Column('prompt_id', sa.Integer(), nullable=False))
    op.drop_index('idx_resids_model_layer_type_created_at', table_name='resids')
    op.create_index('idx_resids_model_prompt_layer_type_created_at', 'resids', ['model_id', 'prompt_id', 'layer', 'type', 'created_at'], unique=False)
    op.create_index(op.f('ix_resids_prompt_id'), 'resids', ['prompt_id'], unique=False)
    op.create_foreign_key('resids_prompt_id_fkey', 'resids', 'prompts', ['prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resids_prompt_id_fkey', 'resids', type_='foreignkey')
    op.drop_index(op.f('ix_resids_prompt_id'), table_name='resids')
    op.drop_index('idx_resids_model_prompt_layer_type_created_at', table_name='resids')
    op.create_index('idx_resids_model_layer_type_created_at', 'resids', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.drop_column('resids', 'prompt_id')
    op.add_column('prompts', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_prompts_text'), table_name='prompts')
    op.create_index('ix_prompts_prompt', 'prompts', ['prompt'], unique=False)
    op.drop_column('prompts', 'text')
    # ### end Alembic commands ###
