"""Add deleted column to directions

Revision ID: dba74d5e9bf7
Revises: 84475365fdb4
Create Date: 2023-07-17 17:13:29.078345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba74d5e9bf7'
down_revision = '84475365fdb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False))
    op.execute('COMMIT')
    op.create_index('idx_directions_user_deleted_created_at', 'directions', ['user_id', 'deleted', 'created_at'], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_directions_user_deleted_created_at', table_name='directions')
    op.drop_column('directions', 'deleted')
    # ### end Alembic commands ###
