"""Make hash column a string again

Revision ID: eebc240f40c4
Revises: 19e0f8750a2c
Create Date: 2023-08-03 20:26:06.365525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebc240f40c4'
down_revision = '19e0f8750a2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_pos_embeds', 'tokens_used_to_compute_hash', existing_type=sa.INTEGER, type_=sa.String)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_pos_embeds', 'tokens_used_to_compute_hash', existing_type=sa.String, type_=sa.INTEGER)
    # ### end Alembic commands ###
