"""Add direction

Revision ID: ef06ff5023b8
Revises: 4fa4ef91aed0
Create Date: 2023-07-07 18:56:40.657910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef06ff5023b8'
down_revision = '4fa4ef91aed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_directions_model_layer_type_time', 'directions', ['model_id', 'layer', 'type', 'created_at'], unique=False)
    op.create_index(op.f('ix_directions_created_at'), 'directions', ['created_at'], unique=False)
    op.create_index(op.f('ix_directions_user_id'), 'directions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directions_user_id'), table_name='directions')
    op.drop_index(op.f('ix_directions_created_at'), table_name='directions')
    op.drop_index('idx_directions_model_layer_type_time', table_name='directions')
    op.drop_table('directions')
    # ### end Alembic commands ###
